ALTER TABLE H_WORKFLOW_TRUST_RULE RENAME COLUMN CREATETIME TO CREATEDTIME;
ALTER TABLE H_WORKFLOW_TRUST_RULE ADD REMARKS VARCHAR2(200);
COMMENT ON COLUMN H_WORKFLOW_TRUST_RULE.REMARKS IS '备注';
ALTER TABLE H_WORKFLOW_TRUST_RULE ADD DELETED NUMBER(1,0);
COMMENT ON COLUMN H_WORKFLOW_TRUST_RULE.DELETED IS '删除标识';

ALTER TABLE H_WORKFLOW_TRUST RENAME COLUMN CREATETIME TO CREATEDTIME;
ALTER TABLE H_WORKFLOW_TRUST ADD MODIFIER VARCHAR2(120);
COMMENT ON COLUMN H_WORKFLOW_TRUST.MODIFIER IS '修改人';
ALTER TABLE H_WORKFLOW_TRUST ADD MODIFIEDTIME timestamp;
COMMENT ON COLUMN H_WORKFLOW_TRUST.MODIFIEDTIME IS '修改时间';
ALTER TABLE H_WORKFLOW_TRUST ADD REMARKS VARCHAR2(200);
COMMENT ON COLUMN H_WORKFLOW_TRUST.REMARKS IS '备注';
ALTER TABLE H_WORKFLOW_TRUST ADD DELETED NUMBER(1,0);
COMMENT ON COLUMN H_WORKFLOW_TRUST.DELETED IS '删除标识';

ALTER TABLE H_TIMER_JOB ADD TRIGGERTIME timestamp;
COMMENT ON COLUMN H_TIMER_JOB.TRIGGERTIME IS '触发时间';
ALTER TABLE H_JOB_RESULT ADD TRIGGERTIME timestamp;
COMMENT ON COLUMN H_JOB_RESULT.TRIGGERTIME IS '触发时间';