CREATE TABLE if not exists `h_biz_query_gantt` (
  `id` varchar(120)  NOT NULL,
  `creater` varchar(120)  DEFAULT NULL,
  `createdTime` datetime DEFAULT NULL,
  `deleted` bit(1) DEFAULT NULL,
  `modifier` varchar(120)  DEFAULT NULL,
  `modifiedTime` datetime DEFAULT NULL,
  `remarks` varchar(200)  DEFAULT NULL,
  `queryId` varchar(36)  DEFAULT NULL,
  `schemaCode` varchar(40)  DEFAULT NULL COMMENT '模型code',
  `startTimePropertyCode` varchar(40)  DEFAULT NULL COMMENT '开始时间对应数据项code',
  `endTimePropertyCode` varchar(40)  DEFAULT NULL COMMENT '结束时间对应数据项code',
  `configJson` longtext  COMMENT '展示配置JSON数据',
  `progressPropertyCode` varchar(40)  DEFAULT NULL COMMENT '进度对应数据项code',
  `titlePropertyCode` varchar(40)  DEFAULT NULL COMMENT '标题对应数据项code',
  `preDependencyPropertyCode` varchar(40)  DEFAULT NULL COMMENT '前置依赖对应数据项code',
  `endDependencyPropertyCode` varchar(40)  DEFAULT NULL COMMENT '后置依赖对应数据项code',
  `levelPropertyCode` varchar(40)  DEFAULT NULL COMMENT '层级关系对应数据项code',
  `milepostCode` varchar(40)  DEFAULT NULL COMMENT '里程碑任务对应数据项code',
  `defaultPrecision` varchar(40)  DEFAULT NULL COMMENT '默认时间精度',
  `sortKey` varchar(40)  DEFAULT NULL COMMENT '排序字段',
  `liableManCode` varchar(40)  DEFAULT NULL COMMENT '责任人对应数据项code',
  `statusCode` varchar(40)  DEFAULT NULL COMMENT '状态对应数据项code',
  PRIMARY KEY (`id`),
  KEY `Idx_schemaCode` (`schemaCode`),
  KEY `Idx_queryid` (`queryId`)
) ENGINE=InnoDB COMMENT='甘特图配置';
